server:
  port: 8050

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 2000MB # default 1M
      max-request-size: 2500MB #default 10M

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000