spring:
  application:
    name: microservice-discovery-eureka-ha

server:
  port: 8762

eureka:
  instance:
    # 当指定profile=eureka02时，主机名是eureka02
    hostname: eureka02
  client:
    registerWithEureka: true # 将该服务自身作为微服务注册到eureka server
    fetchRegistry: true  # 同步其他eureka server的微服务信息
    serviceUrl:
      defaultZone: http://user:password123@eureka01:8761/eureka/,http://user:password123@eureka02:8762/eureka/

# spring security configuration
security:
  basic:
    enabled: true
  user:
    name: user
    password: password123