server:
  port: 8761                    # 指定该Eureka实例的端口

spring:
  application:
    name: microservice-discovery-eureka

# eureka configuration
eureka:
  instance:
    # 当指定profile=peer1时，主机名是peer1
    hostname: peer1
  client:
    registerWithEureka: true # 将该服务自身作为微服务注册到eureka server
    fetchRegistry: true  # 同步其他eureka server的微服务信息
    serviceUrl:
      defaultZone: http://user:password123@peer2:8762/eureka/

# spring security configuration
security:
  basic:
    enabled:  true
  user:
    name: user
    password: password123
