server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie

user :
  userServiceUrl: http://microservice-provider-user/

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@peer1:8761/eureka/,http://user:password123@peer2:8762/eureka/
    instance:
      prefer-ip-address: true