server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie

user :
  userServiceUrl: http://microservice-provider-user/

eureka:
  client:
    service-url:
      # 容器ID
      defaultZone: http://user:password123@eureka01:8761/eureka/,http://user:password123@eureka02:8762/eureka/
    instance:
      prefer-ip-address: true